services:
  user-db:
    image: postgres:16-alpine
    container_name: user-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: matthew
      POSTGRES_PASSWORD: LylitAletAlbay.14
      POSTGRES_DB: user_db
    volumes:
      - ./data/user-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U matthew -d user_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gym-network

  exercise-db:
    image: postgres:16-alpine
    container_name: exercise-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: matthew
      POSTGRES_PASSWORD: LylitAletAlbay.14
      POSTGRES_DB: exercise_db
    volumes:
      - ./data/exercise-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U matthew -d exercise_db" ] # Исправлено на exercise_db
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gym-network

  training-db:
    image: postgres:16-alpine
    container_name: training-db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: matthew
      POSTGRES_PASSWORD: LylitAletAlbay.14
      POSTGRES_DB: training_db
    volumes:
      - ./data/training-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U matthew -d training_db" ] # Исправлено на training_db
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gym-network

  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-db
    restart: unless-stopped
    ports:
      - "5435:5432" # Исправлено на 5435, чтобы не было конфликта
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/keycloak-db:/var/lib/postgresql/data
    networks:
      - gym-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8085
      KC_HOSTNAME_STRICT: "false"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"
    depends_on:
      - keycloak-db
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge